channel: stage
pipelines:
  start:
    event-handlers:
      some-event:
        notify:
          message: '{{ basicMacro(''some-event fired'') }}

            '
  build:
    event-handlers:
      init:
        notify:
          message: '{{ helloWorld(''build is successful'') }}

            '
appPipelinesConfig:
  bases:
  - base1.yaml
  jinja2-macros:
    helloWorld: "{%- macro helloWorld(msg) -%}\n  Hello world msg = {{msg}}\n{%- endmacro\
      \ -%}\n"
  variables:
    myVar1: test
  cicd-contexts:
    stage:
      channel: stage
      pipelines:
        build:
          event-handlers:
            init:
              notify:
                message: '{{ helloWorld(''build is successful'') }}

                  '
jinja2Macros:
  byName:
    basicMacro: "{%- macro basicMacro(msg) -%}\n  This is basicMacro! msg = {{msg}}\n\
      {%- endmacro -%}\n"
    helloWorld: "{%- macro helloWorld(msg) -%}\n  Hello world msg = {{msg}}\n{%- endmacro\
      \ -%}\n"
  all: "{%- macro basicMacro(msg) -%}\n  This is basicMacro! msg = {{msg}}\n{%- endmacro\
    \ -%}{%- macro helloWorld(msg) -%}\n  Hello world msg = {{msg}}\n{%- endmacro\
    \ -%}"
state:
  cicdContextDataId: context-data-id-1
  cicdContextName: stage
  key1: yet a new value
  templateTest: '{{tmplctx.prop1}}'
  fileBody:
    dog: beagle
    bark:
      quality: high
      volume: loud
variables:
  baseVar1: baseVarVal1
  myVar1: test
