channel: stage
pipelines:
  start:
    event-handlers:
      some-event:
        notify:
          message: '{{ basicMacro(''some-event fired in the start pipeline'') }}

            '
  build:
    event-handlers:
      testNotifyEvent:
        notify:
          message: '{{ basicMacro(''build is successful'') }}

            '
          capture-response-data:
          - from: '{{ body.data.channel }}'
            to: state.lastPostedToNotifyChannel
          - from: '{{ body|tojson }}'
            to: state.lastPostedHttpResponse
      testRespondEvent:
        respond:
          if: '{{ state.lastPostedHttpResponse }}'
          url: '{{ (state.lastPostedHttpResponse|from_json).url }}'
          message: 'dummy responder message for {{ state.lastPostedDataRandomId }}

            '
      testSetValuesEvent:
        set-values:
          extractLastPostedNotifyMessage:
            if: "{%- if state.lastPostedHttpResponse -%}\n  1\n{%- endif -%}  \n"
            set:
            - from: '{%- set lastPostedHttpResponse = (state.lastPostedHttpResponse|from_json)
                -%}

                {{- lastPostedHttpResponse.data.message -}}

                '
              to: state.lastPostedNotifyMessage
      testTriggerPipelineEvent:
        trigger-pipeline:
          name: build
          args:
            whatever: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
      testManualChoiceEvent:
        manual-choice:
          title: '{{ basicMacro(''here are my choices'') }}

            '
          choices:
            choiceGroup1:
              header: 'Choice group one:'
              options:
              - text: Choice 1
                value: c1
              - text: Choice 2
                value: c2
            choiceGroup2:
              header: 'Choice group two {{ echo(''blah'') }}:'
              options:
              - text: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
                value: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
appPipelinesConfig:
  bases:
  - base1.yaml
  jinja2-macros:
    helloWorld: "{%- macro helloWorld(msg) -%}\n  Hello world msg = {{msg}}\n{%- endmacro\
      \ -%}\n"
  variables:
    myVar1: test
  cicd-contexts:
    stage:
      channel: stage
      pipelines:
        build:
          event-handlers:
            testNotifyEvent:
              notify:
                message: '{{ basicMacro(''build is successful'') }}

                  '
                capture-response-data:
                - from: '{{ body.data.channel }}'
                  to: state.lastPostedToNotifyChannel
                - from: '{{ body|tojson }}'
                  to: state.lastPostedHttpResponse
            testRespondEvent:
              respond:
                if: '{{ state.lastPostedHttpResponse }}'
                url: '{{ (state.lastPostedHttpResponse|from_json).url }}'
                message: 'dummy responder message for {{ state.lastPostedDataRandomId
                  }}

                  '
            testSetValuesEvent:
              set-values:
                extractLastPostedNotifyMessage:
                  if: "{%- if state.lastPostedHttpResponse -%}\n  1\n{%- endif -%}\
                    \  \n"
                  set:
                  - from: '{%- set lastPostedHttpResponse = (state.lastPostedHttpResponse|from_json)
                      -%}

                      {{- lastPostedHttpResponse.data.message -}}

                      '
                    to: state.lastPostedNotifyMessage
            testTriggerPipelineEvent:
              trigger-pipeline:
                name: build
                args:
                  whatever: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
            testManualChoiceEvent:
              manual-choice:
                title: '{{ basicMacro(''here are my choices'') }}

                  '
                choices:
                  choiceGroup1:
                    header: 'Choice group one:'
                    options:
                    - text: Choice 1
                      value: c1
                    - text: Choice 2
                      value: c2
                  choiceGroup2:
                    header: 'Choice group two {{ echo(''blah'') }}:'
                    options:
                    - text: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
                      value: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
jinja2Macros:
  byName:
    basicMacro: "{%- macro basicMacro(msg) -%}\n  This is basicMacro! msg = {{msg}}\n\
      {%- endmacro -%}\n"
    echo: "{%- macro echo(msg) -%}\n  {{msg}}\n{%- endmacro -%}\n"
    random: "{%- macro random() -%}\n  {{ range(10000, 99999) | random }}\n{%- endmacro\
      \ -%}\n"
    helloWorld: "{%- macro helloWorld(msg) -%}\n  Hello world msg = {{msg}}\n{%- endmacro\
      \ -%}\n"
  all: "{%- macro basicMacro(msg) -%}\n  This is basicMacro! msg = {{msg}}\n{%- endmacro\
    \ -%}{%- macro echo(msg) -%}\n  {{msg}}\n{%- endmacro -%}{%- macro random() -%}\n\
    \  {{ range(10000, 99999) | random }}\n{%- endmacro -%}{%- macro helloWorld(msg)\
    \ -%}\n  Hello world msg = {{msg}}\n{%- endmacro -%}"
state:
  cicdContextDataId: context-data-id-1
  cicdContextName: stage
  key1: value1
  templateTest: '{{tmplctx.prop1}}'
  key2: value2
  fileBody:
    dog: beagle
    bark:
      quality: high
      volume: loud
variables:
  baseVar1: baseVarVal1
  myVar1: test
