channel: stage
pipelines:
  start:
    event-handlers:
      some-event:
        notify:
          message: '{{ basicMacro(''some-event fired in the start pipeline'') }}

            '
  test:
    event-handlers:
      another-event:
        notify:
          message: '{{ basicMacro(''another-event fired in the test pipeline'') }}

            '
          enabled: false
  build:
    generators:
      dockerfile:
        alpine:
          if: '{%- if ''alpine'' in state.gitTag -%}true{%- endif -%}'
          set:
          - key: state.build.targetImageName
            value: '{{state.gitAppName}}'
          - key: state.build.generateDockerfileCmd
            value: "./gendockerfile.sh \\\n    -f alpine:latest \\\n    -x {{state.gitTag}}\
              \ \n    \n"
        centos:
          if: '{%- if ''centos'' in state.gitTag -%}true{%- endif -%}'
          set:
          - key: state.build.targetImageName
            value: '{{state.gitAppName}}'
          - key: state.build.generateDockerfileCmd
            value: "./gendockerfile.sh \\\n    -f centos:latest \\\n    -x {{state.gitTag}}\
              \ \n"
    event-handlers:
      testEvent:
        notify:
          message: '{{ basicMacro(''testEventFired!!! yes...'') }}

            '
      testNotifyEvent:
        notify:
          message: '{{ basicMacro(''build is successful'') }}

            '
          capture-response-data:
          - from: '{{ body.data.channel }}'
            to: state.lastPostedToNotifyChannel
          - from: '{{ body|tojson }}'
            to: state.lastPostedHttpResponse
      testRespondEvent:
        respond:
          someArbitraryKey: lastPostedDataRandomId={{ state.lastPostedDataRandomId
            }}
          if: '{{ state.lastPostedHttpResponse }}'
          url: '{{ (state.lastPostedHttpResponse|from_json).url }}'
          message: 'dummy responder message for {{ state.lastPostedDataRandomId }}

            '
      testSetValuesEvent:
        set-values:
          extractLastPostedNotifyMessage:
            if: "{%- if state.lastPostedHttpResponse -%}\n  1\n{%- endif -%}  \n"
            set:
            - from: '{%- set lastPostedHttpResponse = (state.lastPostedHttpResponse|from_json)
                -%}

                {{- lastPostedHttpResponse.data.message -}}

                '
              to: state.lastPostedNotifyMessage
      testTriggerPipelineEvent:
        trigger-pipeline:
          name: build
          args:
            whatever: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
      testManualChoiceEvent:
        manual-choice:
          title: '{{ basicMacro(''here are my choices'') }}

            '
          choices:
            choiceGroup1:
              header: 'Choice group one:'
              options:
              - text: Choice 1
                value: c1
              - text: Choice 2
                value: c2
            choiceGroup2:
              header: 'Choice group two {{ echo(''blah'') }}:'
              options:
              - text: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
                value: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
      testEmbeddedJsonEvent:
        notify:
          message: 'Here is some JSON from c:\windowspath\test and "quotes" { "dog":"beagle"
            }

            '
  test2:
    event-handlers:
      blah-event:
        manual-choice:
          title: test manual choice with choice-generators
          capture-response-data:
          - from: '{{ body|json_dumps }}'
            to: state.lastPostedHttpResponseFromManualChoice
          choice-generators:
            testGenerator1:
              foreach: state.choiceGeneratorItems
              iterator: currentItem
              template: "testkey-{{currentItem.name}}:\n  header: |\n    {{'{{'}}\
                \ echo('{{currentItem.name}}') {{'}}'}}\n  options:\n    - style:\
                \ primary\n      value: \"{{'{{'}} echo('{{currentItem.name}} {{currentItem.description}}')\
                \ {{'}}'}}\"\n      text: '{{currentItem.name}}'\n    - style: primary\n\
                \      value: \"{{'{{'}} echo('{{currentItem.name}} {{currentItem.description}}')\
                \ {{'}}'}}\"\n      text: '{{currentItem.name}}'\n"
          choices:
            choiceGroup1:
              header: 'Choice group one:'
              options:
              - text: Choice 1
                value: c1
              - text: Choice 2
                value: c2
appPipelinesConfig:
  bases:
  - base1.yaml
  jinja2-macros:
    helloWorld: "{%- macro helloWorld(msg) -%}\n  Hello world msg = {{msg}}\n{%- endmacro\
      \ -%}\n"
  variables:
    myVar1: test
  cicd-contexts:
    stage:
      channel: stage
      pipelines:
        build:
          generators:
            dockerfile:
              alpine:
                if: '{%- if ''alpine'' in state.gitTag -%}true{%- endif -%}'
                set:
                - key: state.build.targetImageName
                  value: '{{state.gitAppName}}'
                - key: state.build.generateDockerfileCmd
                  value: "./gendockerfile.sh \\\n    -f alpine:latest \\\n    -x {{state.gitTag}}\
                    \ \n    \n"
              centos:
                if: '{%- if ''centos'' in state.gitTag -%}true{%- endif -%}'
                set:
                - key: state.build.targetImageName
                  value: '{{state.gitAppName}}'
                - key: state.build.generateDockerfileCmd
                  value: "./gendockerfile.sh \\\n    -f centos:latest \\\n    -x {{state.gitTag}}\
                    \ \n"
          event-handlers:
            testEvent:
              notify:
                message: '{{ basicMacro(''testEventFired!!! yes...'') }}

                  '
            testNotifyEvent:
              notify:
                message: '{{ basicMacro(''build is successful'') }}

                  '
                capture-response-data:
                - from: '{{ body.data.channel }}'
                  to: state.lastPostedToNotifyChannel
                - from: '{{ body|tojson }}'
                  to: state.lastPostedHttpResponse
            testRespondEvent:
              respond:
                someArbitraryKey: lastPostedDataRandomId={{ state.lastPostedDataRandomId
                  }}
                if: '{{ state.lastPostedHttpResponse }}'
                url: '{{ (state.lastPostedHttpResponse|from_json).url }}'
                message: 'dummy responder message for {{ state.lastPostedDataRandomId
                  }}

                  '
            testSetValuesEvent:
              set-values:
                extractLastPostedNotifyMessage:
                  if: "{%- if state.lastPostedHttpResponse -%}\n  1\n{%- endif -%}\
                    \  \n"
                  set:
                  - from: '{%- set lastPostedHttpResponse = (state.lastPostedHttpResponse|from_json)
                      -%}

                      {{- lastPostedHttpResponse.data.message -}}

                      '
                    to: state.lastPostedNotifyMessage
            testTriggerPipelineEvent:
              trigger-pipeline:
                name: build
                args:
                  whatever: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
            testManualChoiceEvent:
              manual-choice:
                title: '{{ basicMacro(''here are my choices'') }}

                  '
                choices:
                  choiceGroup1:
                    header: 'Choice group one:'
                    options:
                    - text: Choice 1
                      value: c1
                    - text: Choice 2
                      value: c2
                  choiceGroup2:
                    header: 'Choice group two {{ echo(''blah'') }}:'
                    options:
                    - text: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
                      value: '{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}'
            testEmbeddedJsonEvent:
              notify:
                message: 'Here is some JSON from c:\windowspath\test and "quotes"
                  { "dog":"beagle" }

                  '
        test:
          event-handlers:
            another-event:
              notify:
                enabled: false
        test2:
          event-handlers:
            blah-event:
              manual-choice:
                title: test manual choice with choice-generators
                capture-response-data:
                - from: '{{ body|json_dumps }}'
                  to: state.lastPostedHttpResponseFromManualChoice
                choice-generators:
                  testGenerator1:
                    foreach: state.choiceGeneratorItems
                    iterator: currentItem
                    template: "testkey-{{currentItem.name}}:\n  header: |\n    {{'{{'}}\
                      \ echo('{{currentItem.name}}') {{'}}'}}\n  options:\n    - style:\
                      \ primary\n      value: \"{{'{{'}} echo('{{currentItem.name}}\
                      \ {{currentItem.description}}') {{'}}'}}\"\n      text: '{{currentItem.name}}'\n\
                      \    - style: primary\n      value: \"{{'{{'}} echo('{{currentItem.name}}\
                      \ {{currentItem.description}}') {{'}}'}}\"\n      text: '{{currentItem.name}}'\n"
                choices:
                  choiceGroup1:
                    header: 'Choice group one:'
                    options:
                    - text: Choice 1
                      value: c1
                    - text: Choice 2
                      value: c2
jinja2Macros:
  byName:
    basicMacro: "{%- macro basicMacro(msg) -%}\n  This is basicMacro! msg = {{msg}}\n\
      {%- endmacro -%}\n"
    echo: "{%- macro echo(msg) -%}\n  {{msg}}\n{%- endmacro -%}\n"
    random: "{%- macro random() -%}\n  {{ range(10000, 99999) | random }}\n{%- endmacro\
      \ -%}\n"
    helloWorld: "{%- macro helloWorld(msg) -%}\n  Hello world msg = {{msg}}\n{%- endmacro\
      \ -%}\n"
  all: "{%- macro basicMacro(msg) -%}\n  This is basicMacro! msg = {{msg}}\n{%- endmacro\
    \ -%}{%- macro echo(msg) -%}\n  {{msg}}\n{%- endmacro -%}{%- macro random() -%}\n\
    \  {{ range(10000, 99999) | random }}\n{%- endmacro -%}{%- macro helloWorld(msg)\
    \ -%}\n  Hello world msg = {{msg}}\n{%- endmacro -%}"
state:
  cicdContextDataId: context-data-id-1
  cicdContextName: stage
  key1: value1
  gitTag: myapp-alpine-1.5.9
  gitAppName: my-application
  build:
    targetImageName: my-application
    generateDockerfileCmd: "./gendockerfile.sh \\\n    -f alpine:latest \\\n    -x\
      \ myapp-alpine-1.5.9"
variables:
  baseVar1: baseVarVal1
  myVar1: test
