
######################
#
# CICD Contexts
#
######################
cicd-contexts:

  #############################################################################
  #
  # DEV CICD Context
  #
  ##############################################################################
  dev:

    # The slack channel this context integrates with
    channel: cicdstatemgr-dev

    # all of the pipelines in this context
    pipelines:

      #---------------------------------------------------
      #
      # START pipeline
      #
      #---------------------------------------------------
      start:

        event-handlers:

          #~~~~~~~~~~~~~~~~~~~~~~~
          # START event -> init
          #~~~~~~~~~~~~~~~~~~~~~~~
          init:

            # we immediately respond, only if from Slack (via response URL) 
            respond:
              if: "{{ event.data.params.request.body.api_app_id }}"
              url: "{{ event.data.params.request.body.response_url }}"
              message: |
                {{ responderMessage(event.data.params.request.body) }}

            set-values: 
              # set state values from an Github triggered start
              gitValues:
                if: "{{ event.data.params.request.body.head_commit }}"
                set:
                  - from: "{{ event.data.params.request.body.head_commit.message }}"
                    to: "state.commitMsg"

                  - from: "{{ event.data.params.request.body.after }}"  
                    to: "state.commitId"

                  - from: "{{ event.data.params.request.body.repository.clone_url }}"  
                    to: "state.gitCloneUrl"

              # set state values from an Slack triggered (button press) posted start
              slackValues:
                if: "{{ event.data.params.request.body.api_app_id }}"
                set:
                  - from: "SANITIZED"
                    to: "state.start.{{event.data.params.pipelineRunUid}}.params.request.body.token"

                  - from: "{{ event.data.params.request.body.user.id }}"
                    to: "state.start.{{event.data.params.pipelineRunUid}}.slack.user.id"

                  - from: "{{ event.data.params.request.body.user.name }}"
                    to: "state.start.{{event.data.params.pipelineRunUid}}.slack.user.name"
                    
                  - from: "{{ event.data.params.request.body.user.username }}"
                    to: "state.start.{{event.data.params.pipelineRunUid}}.slack.user.username"

                  - from: "{{ event.data.params.request.body.container.message_ts }}"
                    to: "state.start.{{event.data.params.pipelineRunUid}}.slack.message_ts"

                  - from: "{{ event.data.params.request.body.container.thread_ts }}"
                    to: "state.start.{{event.data.params.pipelineRunUid}}.slack.thread_ts"

                  - from: "{{ event.data.params.request.body.container.channel_id }}"
                    to: "state.start.{{event.data.params.pipelineRunUid}}.slack.channel_id"

                  - from: "{{ configData.slack.orgUrl }}/archives/{{ event.data.params.request.body.container.channel_id }}/p{{ event.data.params.request.body.container.message_ts }}?{{ event.data.params.request.body.container.thread_ts }}&cid={{ event.data.params.request.body.container.channel_id }}"
                    to: "state.start.{{event.data.params.pipelineRunUid}}.slack.message_url"

          #~~~~~~~~~~~~~~~~~~~~~~~
          # START event -> success
          #~~~~~~~~~~~~~~~~~~~~~~~
          success:
            notify:
              message: |
                {{newCicdContextSuccessMessage()}}

            trigger-pipeline:
              name: build
              args:
                gitCloneUrl: "{{state.gitCloneUrl}}"

          #~~~~~~~~~~~~~~~~~~~~~~~
          # START event -> failure
          #~~~~~~~~~~~~~~~~~~~~~~~
          failure:
            notify:
              message: |
                :x: START NEW CICD CONTEXT FAILED 
                {{statusLink()}}




      #---------------------------------------------------
      #
      # BUILD pipeline
      #
      #---------------------------------------------------
      build:

        event-handlers:

          #~~~~~~~~~~~~~~~~~~~~~~~
          # BUILD event -> init
          #~~~~~~~~~~~~~~~~~~~~~~~
          init:
            notify:
              message: |
                :information_source: NEW GIT TAG: *{{state.gitAppName}}:{{state.appTag}}* 
                has been detected, triggered by {{ event.data.security.invokerUid }}, Starting image build/push. 
                {{statusLink()}}

          #~~~~~~~~~~~~~~~~~~~~~~~
          # BUILD event -> success
          #~~~~~~~~~~~~~~~~~~~~~~~
          success:
            notify:
              message: |
                :white_check_mark: SUCCESSFULLY BUILT AND PUSHED {{state.gitAppName}}:{{state.appTag}}. 
                {{statusLink()}}

            manual-choice:
              title: |
                {{ successManualChoicesTitle() }}
              choices:
                validate:
                  header: "Validate image: {{state.gitAppName}}:{{state.appTag}}:"
                  options:
                    - style: primary
                      value: "{{ validateButtonValue() }}"
                      text: validate
                test:
                  header: "Test image: {{state.gitAppName}}:{{state.appTag}}:"
                  options:
                    - style: primary
                      value: "{{ testButtonValue() }}"
                      text: test
                deploy:
                  header: "{{ deployHeader() }}"
                  options:
                    - style: primary
                      value: "{{ deployButtonValue(state.gitAppName, state.appTag) }}"
                      text: "{{ deployButtonLabel() }}"

          #~~~~~~~~~~~~~~~~~~~~~~~
          # BUILD event -> failure
          #~~~~~~~~~~~~~~~~~~~~~~~
          failure:
            notify:
              message: |
                :x: BUILD/PUSH FAILED. 
                {{statusLink()}}
          

      #---------------------------------------------------
      #
      # VALIDATE pipeline
      #
      #---------------------------------------------------
      validate:
        event-handlers:

          #~~~~~~~~~~~~~~~~~~~~~~~
          # VALIDATE event -> init
          #~~~~~~~~~~~~~~~~~~~~~~~
          init:

            # we immediately respond, only if from Slack (via response URL) 
            respond:
              if: "{{ event.data.params.request.body.api_app_id }}"
              url: "{{ event.data.params.request.body.response_url }}"
              message: |
                {{ responderMessage(event.data.params.request.body) }}

            set-values: 

              # set state values from an Slack triggered (button press) posted start
              slackValues:
                if: "{{ event.data.params.request.body.api_app_id }}"
                set:
                  - from: "SANITIZED"
                    to: "state.validate.{{event.data.params.pipelineRunUid}}.params.request.body.token"

                  - from: "{{ event.data.params.request.body.user.id }}"
                    to: "state.validate.{{event.data.params.pipelineRunUid}}.slack.user.id"

                  - from: "{{ event.data.params.request.body.user.name }}"
                    to: "state.validate.{{event.data.params.pipelineRunUid}}.slack.user.name"
                    
                  - from: "{{ event.data.params.request.body.user.username }}"
                    to: "state.validate.{{event.data.params.pipelineRunUid}}.slack.user.username"

                  - from: "{{ event.data.params.request.body.container.message_ts }}"
                    to: "state.validate.{{event.data.params.pipelineRunUid}}.slack.message_ts"

                  - from: "{{ event.data.params.request.body.container.thread_ts }}"
                    to: "state.validate.{{event.data.params.pipelineRunUid}}.slack.thread_ts"

                  - from: "{{ event.data.params.request.body.container.channel_id }}"
                    to: "state.validate.{{event.data.params.pipelineRunUid}}.slack.channel_id"

                  - from: "{{ configData.slack.orgUrl }}/archives/{{ event.data.params.request.body.container.channel_id }}/p{{ event.data.params.request.body.container.message_ts }}?{{ event.data.params.request.body.container.thread_ts }}&cid={{ event.data.params.request.body.container.channel_id }}"
                    to: "state.validate.{{event.data.params.pipelineRunUid}}.slack.message_url"


            notify:
              message: |
                :information_source: ({{state.cicdVersion}}) STARTING VALIDATION. 
                {{statusLink()}}
            
          #~~~~~~~~~~~~~~~~~~~~~~~
          # VALIDATE event -> success
          #~~~~~~~~~~~~~~~~~~~~~~~
          success:
            notify:
              message: |
                :white_check_mark: ({{state.cicdVersion}}) SUCCESSFULLY VALIDATED {{state.gitAppName}}:{{state.appTag}}

                ```
                {{ event.data.trivy.scanResults }}
                ```

                {{statusLink()}}

            manual-choice:
              title: |
                {{ successManualChoicesTitle() }}
              choices:
                test:
                  header: "{{ testHeader() }}"
                  options:
                    - style: primary
                      value: "{{ testButtonValue() }}"
                      text: test
                deploy:
                  header: "{{ deployHeader() }}"
                  options:
                    - style: primary
                      value: "{{ deployButtonValue() }}"
                      text: "{{ deployButtonLabel() }}"

          #~~~~~~~~~~~~~~~~~~~~~~~
          # VALIDATE event -> failure
          #~~~~~~~~~~~~~~~~~~~~~~~
          failure:
            notify:
              message: |
                :x: ({{state.cicdVersion}}) VALIDATION FAILED. 
                {{statusLink()}}
            




      #---------------------------------------------------
      #
      # TEST pipeline
      #
      #---------------------------------------------------
      test:

        event-handlers:

          #~~~~~~~~~~~~~~~~~~~~~~~
          # TEST event -> init
          #~~~~~~~~~~~~~~~~~~~~~~~
          init:

            # we immediately respond, only if from Slack (via response URL) 
            respond:
              if: "{{ event.data.params.request.body.api_app_id }}"
              url: "{{ event.data.params.request.body.response_url }}"
              message: |
                {{ responderMessage(event.data.params.request.body) }}

            set-values: 

              # set state values from an Slack triggered (button press) posted start
              slackValues:
                if: "{{ event.data.params.request.body.api_app_id }}"
                set:
                  - from: "SANITIZED"
                    to: "state.test.{{event.data.params.pipelineRunUid}}.params.request.body.token"

                  - from: "{{ event.data.params.request.body.user.id }}"
                    to: "state.test.{{event.data.params.pipelineRunUid}}.slack.user.id"

                  - from: "{{ event.data.params.request.body.user.name }}"
                    to: "state.test.{{event.data.params.pipelineRunUid}}.slack.user.name"
                    
                  - from: "{{ event.data.params.request.body.user.username }}"
                    to: "state.test.{{event.data.params.pipelineRunUid}}.slack.user.username"

                  - from: "{{ event.data.params.request.body.container.message_ts }}"
                    to: "state.test.{{event.data.params.pipelineRunUid}}.slack.message_ts"

                  - from: "{{ event.data.params.request.body.container.thread_ts }}"
                    to: "state.test.{{event.data.params.pipelineRunUid}}.slack.thread_ts"

                  - from: "{{ event.data.params.request.body.container.channel_id }}"
                    to: "state.test.{{event.data.params.pipelineRunUid}}.slack.channel_id"

                  - from: "{{ configData.slack.orgUrl }}/archives/{{ event.data.params.request.body.container.channel_id }}/p{{ event.data.params.request.body.container.message_ts }}?{{ event.data.params.request.body.container.thread_ts }}&cid={{ event.data.params.request.body.container.channel_id }}"
                    to: "state.test.{{event.data.params.pipelineRunUid}}.slack.message_url"

            notify:
              message: |
                :information_source: ({{state.cicdVersion}}) STARTING TESTING. 
                {{statusLink()}}
            
          #~~~~~~~~~~~~~~~~~~~~~~~
          # TEST event -> success
          #~~~~~~~~~~~~~~~~~~~~~~~
          success:
            notify:
              message: |
                :white_check_mark: ({{state.cicdVersion}}) SUCCESSFULLY TESTED {{state.gitAppName}}:{{state.appTag}}. 
                {{statusLink()}}
            manual-choice:
              title: |
                {{ successManualChoicesTitle() }}
              choices:
                validate:
                  header: "{{ validateHeader() }}"
                  options:
                    - style: primary
                      value: "{{ validateButtonValue() }}"
                      text: validate
                deploy:
                  header: "{{ deployHeader() }}"
                  options:
                    - style: primary
                      value: "{{ deployButtonValue() }}"
                      text: "{{ deployButtonLabel() }}"
          

          #~~~~~~~~~~~~~~~~~~~~~~~
          # TEST event -> failure
          #~~~~~~~~~~~~~~~~~~~~~~~
          failure:
            notify:
              message: |
                :x: ({{state.cicdVersion}}) TESTING FAILED. 
                {{statusLink()}}
          



      #---------------------------------------------------
      #
      # DEPLOY pipeline
      #
      #---------------------------------------------------
      deploy:

        deployTask:
          targetNamespace: apps-dev

        event-handlers:

          #~~~~~~~~~~~~~~~~~~~~~~~
          # DEPLOY event -> init
          #~~~~~~~~~~~~~~~~~~~~~~~
          init:

            # we immediately respond, only if from Slack (via response URL) 
            respond:
              if: "{{ event.data.params.request.body.api_app_id }}"
              url: "{{ event.data.params.request.body.response_url }}"
              message: |
                {{ responderMessage(event.data.params.request.body) }}

            set-values: 

              # set state values from an Slack triggered (button press) posted start
              slackValues:
                if: "{{ event.data.params.request.body.api_app_id }}"
                set:
                  - from: "SANITIZED"
                    to: "state.deploy.{{event.data.params.pipelineRunUid}}.params.request.body.token"

                  - from: "{{ event.data.params.request.body.user.id }}"
                    to: "state.deploy.{{event.data.params.pipelineRunUid}}.slack.user.id"

                  - from: "{{ event.data.params.request.body.user.name }}"
                    to: "state.deploy.{{event.data.params.pipelineRunUid}}.slack.user.name"
                    
                  - from: "{{ event.data.params.request.body.user.username }}"
                    to: "state.deploy.{{event.data.params.pipelineRunUid}}.slack.user.username"

                  - from: "{{ event.data.params.request.body.container.message_ts }}"
                    to: "state.deploy.{{event.data.params.pipelineRunUid}}.slack.message_ts"

                  - from: "{{ event.data.params.request.body.container.thread_ts }}"
                    to: "state.deploy.{{event.data.params.pipelineRunUid}}.slack.thread_ts"

                  - from: "{{ event.data.params.request.body.container.channel_id }}"
                    to: "state.deploy.{{event.data.params.pipelineRunUid}}.slack.channel_id"

                  - from: "{{ configData.slack.orgUrl }}/archives/{{ event.data.params.request.body.container.channel_id }}/p{{ event.data.params.request.body.container.message_ts }}?{{ event.data.params.request.body.container.thread_ts }}&cid={{ event.data.params.request.body.container.channel_id }}"
                    to: "state.deploy.{{event.data.params.pipelineRunUid}}.slack.message_url"


            notify:
              message: |
                :information_source: STARTING DEPLOY: 
                  
                image: *{{state.gitAppName}}:{{event.data.params.targetAppTag}}*
                target namespace: *{{pipelines.deploy.deployTask.targetNamespace}}*

                {{statusLink()}}

   
          #~~~~~~~~~~~~~~~~~~~~~~~
          # DEPLOY event -> failure
          #~~~~~~~~~~~~~~~~~~~~~~~
          failure:
            notify:
              message: |
                {{ deploymentFailedMessage() }}
            manual-choice:
              title: |
                {{ rollbackManualChoicesTitle() }}
              choices:
                rollback:
                  header: |
                    {{ rollbackHeader() }}
                  options:
                    - style: primary
                      value: "{{ rollbackButtonValue() }}"
                      text: "rollback"

          #~~~~~~~~~~~~~~~~~~~~~~~
          # DEPLOY event -> success
          #~~~~~~~~~~~~~~~~~~~~~~~
          success:
            notify:
              message: |
                {{ deploymentSuccessMessage() }}
            
            manual-choice:
              title: |
                {{ successManualChoicesTitle() }}
              choices:
                change-context:
                  header: "Route to {{state.gitAppName}}:{{state.appTag}} to different CICD context:"
                  options:
                    - style: primary
                      value: "{{ changeContextButtonValue('prod') }}"
                      text: prod


