
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-v1
spec:
  serviceAccountName: tekton-triggers-admin
  serviceType: NodePort
  triggers:

    # --------------------------------------------------
    # Handle Github webhook call from tag push
    # --------------------------------------------------
    - name: start-v1-interceptor
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
              - push

        - cel:
            overlays:

              - key: intercepted.invokedByPrincipalId
                expression: "body.pusher.email"
                
              - key: intercepted.gitAppName
                expression: "body.repository.name"

              - key: intercepted.appTag
                expression: "body.ref.split('/')[2]" # refs/tags/9.9.9-1--1-3 | develop etc

              - key: intercepted.commitMsg
                expression: "body.head_commit.message" 

              - key: intercepted.commitId
                expression: "body.head_commit.id"

              - key: intercepted.cloneUrl
                expression: "body.repository.clone_url"


      bindings:
        - ref: build-via-git-v1
          name: build-via-git-v1
      template:
        name: build-v1

---

