apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-aliases
  namespace: kube-system
  labels:
    kubernetes.io/minikube-addons: registry-aliases
    addonmanager.kubernetes.io/mode: Reconcile
data:
  # Add additonal hosts seperated by new-line
  registryAliases: >-
    bitsofinfo.registry.local
  # default registry address in minikube when enabled via minikube addons enable registry
  registrySvc: registry.kube-system.svc.cluster.local

