bases:
  - base1.yaml

jinja2-macros: 

  helloWorld: |
    {%- macro helloWorld(msg) -%}
      Hello world msg = {{msg}}
    {%- endmacro -%}

variables:
  myVar1: "test"

cicd-contexts:

  stage:
    channel: stage

    pipelines:
      build:
        event-handlers:

          testEvent:

            notify:
              message: |
                {{ basicMacro('build is successful') }}

              capture-response-data:
                - from: "{{ body.data.channel }}"
                  to: state.lastPostedToNotifyChannel
                - from: "{{ body|from_json }}"
                  to: state.lastPostedHttpResponse

            respond:
              if: "{{ event.data.params.request.body.api_app_id }}"
              url: "{{ event.data.params.request.body.response_url }}"
              message: |
                {{ responderMessage(event.data.params.request.body) }}

            set-values: 
              # set state values from an Github triggered start
              gitValues:
                if: "{{ event.data.params.request.body.head_commit }}"
                set:
                  - from: "{{ event.data.params.request.body.head_commit.message }}"
                    to: "state.commitMsg"

                  - from: "{{ event.data.params.request.body.after }}"  
                    to: "state.commitId"

                  - from: "{{ event.data.params.request.body.repository.clone_url }}"  
                    to: "state.gitCloneUrl"

            # see config.yaml for additional headers
            # and auto-args that will supplement what is
            # specified here
            trigger-pipeline:
              name: build
              args:
                whatever: "{{state.postedData.headers.userAgent}}"

            manual-choice:
              title: |
                {{ basicMacro('here are my choices') }}
              choices:
                choiceGroup1:
                  header: "Choice group one:"
                  options:
                    - text: "Choice 1"
                      value: "c1"
                    - text: "Choice 2"
                      value: "c2"

                choiceGroup2:
                  header: "Choice group two {{ echo('blah') }}:"
                  options:
                    - text: "{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}"
                      value: "{{state.postedData[state.lastPostedDataRandomId].headers.userAgent}}"